### ISSUE TITLE
VR mode issue

### ISSUE THREAD

**Issue by wsljt19940218** [tqjxlm/Atlas#6]
I download dev release,but the VR mode doesn't work!

What i dit is as follows:
1. open Atlas.exe
2. switch to 3D mode
3. click effect-VR mode

Than the SteamVR running,and a console windows appear and disappear Immediately！
By the way,i use HTC VIVE.

**Comment by tqjxlm** [comment]
A fix has been pushed to a1268e7

Could you please see if it's working in your environment?

By the way, the basic interaction is:
* Toggle the plugin and rotate your headset to find the scene.
* trackpad click ↑↓←→：paning
* trigger + trackpad click ←→: rotating
* trigger + trackpad click↑↓: zooming

**Comment by tqjxlm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix VRMode](https://trello.com/c/rTKXtCkq/49-fix-vrmode)
